### DISCUSSION TITLE
Setting up GPIO pins in openHAB

### DISCUSSION THREAD

**Discussion by CrazyIvan359** [CrazyIvan359/mqttany#107] [Troubleshooting] [answered]
Discussion started in #79 by [@Veldhius123](https://github.com/Veldhuis123)

i have change the configuration but it don't work.

at the moment I am not coping very well with it, but it is getting better
```
gpio:
  polling interval: 60
  debounce: 10

  channel1:
    pin: 26
    name: '{relay}'
    pin mode: 'output'
    resistor: 'off'
```

this is my openHab configuration

```
UID: mqtt:topic:openhab:relay
label: Generic MQTT Thing
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:openhab
channels:
  - id: channel1
    channelTypeUID: mqtt:switch
    label: test
    description: ""
    configuration:
      commandTopic: 10.0.10.200/relay/1/set
      stateTopic: 10.0.10.200/relay/1

```

**Comment by CrazyIvan359** [comment, marked as answer]
I suggest you read through the documentation of MQTTany and the MQTT binding in openHAB to get more familiar with both. You will also find examples for the MQTT binding on the openHAB forum.

I will give you some examples for the pin you are trying to setup to get you started.

The `root topic` defaults to being the same as the `client id`, which defaults to the hostname of the system. You have your topics in openHAB using a root of `10.0.10.200`, but that is the address of your MQTT server. From your command prompt `pi@raspberrypi: ~ $` you can see that the hostname is `raspberrypi`, therefore MQTTany is connecting using the name `raspberrypi` and the root topic is also `raspberrypi`.

The rest of the topic is also wrong, as I stated in my response in #79. You have removed the `topic` option and added the `name` option, but it still isn't going to give you the topic you have in openHAB, that topic is not possible.

If I understand correctly, you want to have several numbered relays configured. Based on that you could use this configuration:
```yaml
gpio:
  channels:
    pin: [26, 27]  # a list of the pins your relays are connected to, in the order you want them numbered
    name: 'channel{index}'
    pin mode: output
    first index: 1
```

That will give you GPIO26 on the topic `raspberrypi/gpio/channel1` and GPIO27 on topic `raspberrypi/gpio/channel2`. Bring that into openHAB like this:

```yaml
UID: mqtt:topic:openhab:channel1
label: Channel 1
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:openhab
channels:
  - id: relay
    channelTypeUID: mqtt:switch
    label: Channel 1 Relay
    description: ""
    configuration:
      commandTopic: raspberrypi/gpio/channel1/set
      stateTopic: raspberrypi/gpio/channel1
      on: ON
      off: OFF
```

```yaml
UID: mqtt:topic:openhab:channel2
label: Channel 2
thingTypeUID: mqtt:topic
configuration: {}
bridgeUID: mqtt:broker:openhab
channels:
  - id: relay
    channelTypeUID: mqtt:switch
    label: Channel 2 Relay
    description: ""
    configuration:
      commandTopic: raspberrypi/gpio/channel2/set
      stateTopic: raspberrypi/gpio/channel2
      on: ON
      off: OFF
```
