### ISSUE TITLE
no rx/tx of negative temperatures

### ISSUE THREAD

**Issue by EKNYESE** [CrazyIvan359/mqttany#164]
### Describe the bug
no temperature-values are sent when sensor sends negative temperature-values to system

### Expected behavior
Temperartures should also be send via mqtt, when DS18B20-sensor is set to temperatures < 0°C 

### Environment
- MQTTany version: 0.14.3-dev (as it is send via mqtt; my last log-file has no version transmitted [...} - only the same [INFO] regarding connection, see below)
- Platform: Raspberry Pi 4B [4GB] running openHABian

### Configuration
```yaml
######## OneWire Module ########
onewire:

  ### Bus Interface
  bus interface: 'w1'

  ### Polling Interval
  polling interval: 10 # interval in seconds to poll all devices

  ### Bus Scan
  # Scan bus for any unconfigured devices and add them
  #bus scan: true

  #id-28-0000001bec9f:
    #address: '28-0000001bec9f'
  #id-28-0000001c6cec:
    #address: '28-0000001c6cec'
  id-28-032097799588:
    address: '28-032097799588'
  #id-28-032097796842:
    #address: '28-032097796842'
  id-28-000005db3945:
    address: '28-000005db3945'
  #id-28-3c01d6074534:
    #address: '28-3c01d6074534'
  id-28-030497943961:
    address: '28-030497943961'

```

### Logs
```text
2025-02-16 16:41:15,440 [INFO ] [mqtt                    ] Connected to broker 'openHABianRPi4:1883'
```
